# Generated by Django 4.2 on 2025-03-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_quizquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
    ]
