# Generated by Django 4.2 on 2025-04-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
