# Generated by Django 4.2 on 2025-04-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_grade_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
