# Generated by Django 4.2 on 2025-04-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_quizquestion_explanation_delete_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='subject',
            field=models.CharField(choices=[('math', 'Math'), ('physics', 'Physics'), ('history', 'Informatics')], default='math', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_option',
            field=models.CharField(max_length=1),
        ),
    ]
